name: analogy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - r-base=4.1.2

  # Python packages
  - pandas
  - ipykernel
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn

  # R packages (via conda-forge)
  - r-nbclust
  - r-ggpubr