name: analogy
channels:
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - appnope=0.1.4
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.2.25
  - cairo=1.18.4
  - cctools_osx-arm64=1010.6
  - clang=20.1.3
  - clang-20=20.1.3
  - clang_impl_osx-arm64=20.1.3
  - clang_osx-arm64=20.1.3
  - clangxx=20.1.3
  - clangxx_impl_osx-arm64=20.1.3
  - clangxx_osx-arm64=20.1.3
  - comm=0.2.2
  - compiler-rt=20.1.3
  - compiler-rt_osx-arm64=20.1.3
  - curl=8.13.0
  - debugpy=1.8.11
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.7.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gfortran_impl_osx-arm64=13.3.0
  - gfortran_osx-arm64=13.3.0
  - glob2=0.7
  - gmp=6.3.0
  - graphite2=1.3.13
  - gsl=2.7
  - harfbuzz=11.1.0
  - icu=75.1
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - isl=0.26
  - jedi=0.19.2
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - ld64_osx-arm64=951.9
  - lerc=4.0.0
  - libasprintf=0.23.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.3
  - libcurl=8.13.0
  - libcxx=20.1.3
  - libcxx-devel=20.1.3
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.4
  - libgettextpo=0.23.1
  - libgfortran=14.2.0
  - libgfortran-devel_osx-arm64=13.3.0
  - libgfortran5=14.2.0
  - libglib=2.84.0
  - libiconv=1.18
  - libintl=0.23.1
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.3
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsodium=1.0.18
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxml2=2.13.7
  - libzlib=1.3.1
  - llvm-openmp=20.1.3
  - llvm-tools=20.1.3
  - llvm-tools-20=20.1.3
  - make=4.4.1
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=2.2.4
  - numpy-base=2.2.4
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.2.3
  - pango=1.56.3
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - pixman=0.44.2
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.13
  - pytz=2024.1
  - pyzmq=26.2.0
  - r-base=4.4.3
  - r-nbclust=3.0.1
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=72.1.0
  - sigtool=0.1.3
  - six=1.17.0
  - sqlite=3.49.1
  - stack_data=0.6.3
  - tapi=1300.6.5
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tktable=2.10
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - tzdata=2025a
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
